---
title: "yojoa heat map"
author: "Matthew Ross"
date: "4/11/2022"
output: html_document
---

```{r}
library(tidyverse)
library(sf) # new good
library(mapview)
library(lubridate)
library(osmdata)
library(raster) #dead to me
library(sp) # also dead to me
library(gstat)

```


# Data read
```{r}
# Read in points
y <- read_csv('data/Yojoaheatmapfile.csv') 
  

ys <- st_as_sf(y,coords=c('longitude','latitude'),crs=4326) 

ys.m <- st_transform(ys,crs=26716) %>%
  mutate(x=st_coordinates(.)[,1],
         y=st_coordinates(.)[,2])



# Get county 
bb <- getbb('Santa Barbara, Honduras')

#Download Lago de Yojoa
lake <- opq(bbox=bb) %>%
add_osm_feature(key = 'natural', value = 'water') %>%
  osmdata_sf() %>%
  .$osm_polygons %>%
  filter(name == 'Lago de Yojoa') %>%
  st_transform(26716)


#Get bbox info for yojoa
yo_box <- st_bbox(lake)

mapview(ys,zcol='Cu_mg_kg') + mapview(lake) + mapview(yo_box)
```

## Make a heatmap
```{r}

lake.sp <- as(lake,'Spatial')
lake.raster <- raster(lake.sp,res=100)
g <- as(lake.raster,'SpatialGrid')


y.sp <- as(ys.m,'Spatial')


metals = c('Cu_mg_kg','Zn_mg_kg','Cd_mg_kg','Pb_mg_kg')

i=1
for(i in 1:length(metals)){
  
  
  formula = as.formula(paste(metals[i], 1,sep='~'))
  cu_s <- gstat(id=metals[i],formula=formula,data=y.sp)
  z <- interpolate(lake.raster,cu_s) %>% round(.,1)
  
  z <- mask(z,lake.sp)
  
  
  
  
  cu <- mapview(z,na.col=NA,col.regions=mapviewGetOption('vector.palette')) + 
    mapview(ys.m,zcol=metals[i])
  mapshot(cu,url=paste0(metals[i],'.html'))
}
cu
```


# The new way

```{r}
library(stars)

lake_stars <- st_bbox(lake) %>% 
  st_as_stars(dx=100) %>% 
  st_crop(lake)

interp = idw(Zn_mg_kg~1, y.sp, lake_stars)


mapview(interp) + mapview(y.sp, zcol = "Zn_mg_kg")
```

# Variogram

```{r}

v_zn = variogram(Zn_mg_kg~1, y.sp)

v.m = fit.variogram(v_zn, vgm(1, 'Gau', 50, 1))

plot(v_zn, v.m, plot.numbers = TRUE)

interp_krig = krige(Zn_mg_kg~1, y.sp, lake_stars)
```

